# Define the version of the Docker Compose file syntax
version: '3'

# Define the services that will be run in the Docker environment
services:

  # Base Station Service
  basestation:
    container_name: basestation
    # Environment variables
    environment:
      ALL_TOGETHER: "True"
      FIRST_COUNTER: "True"
      USE_FOLDER_FOR_SAVE: "True"

    # Build from Dockerfile in ./BaseStation directory
    build:
      context: ./BaseStation
      dockerfile: Dockerfile
    image: basestation-exp:1.1

    # Map port 8000 in the container to port 8000 on the host
    ports:
      - "8000:8000"

    # Mount ./data directory to /data in the container
    volumes:
      - ./data:/data

    # Network mode and IP address
    networks:
      internet:

  # Drone Service
  edge:
    container_name: drone
    # Environment variables
    environment:
      ALL_TOGETHER: "True"
      NUMBER_OF_IMAGES: "2"

    # Build from Dockerfile in ./Drone directory
    build:
      context: Drone
      dockerfile: Dockerfile
    image: drone-exp:1.0

    # Network mode and network dependencies
    networks:
      - internet
    depends_on:
      - basestation

  # Cloud Service
  cloud:
    container_name: cloud
    # Build from Dockerfile in ./Cloud directory
    build:
      context: ./Cloud
      dockerfile: Dockerfile
    image: cloud-exp:1.2

    # Map port 8080 in the container to port 8080 on the host
    ports:
      - "8080:8080"

    # Mount ./data directory to /data in the container
    volumes:
      - ./data:/data

    # Network mode and IP address
    networks:
      internet:

# Networks
networks:
  internet:

